// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  angular.module("playgroundCoffeeAngularApp").controller("MainCtrl", function($scope) {
    var updateClock;
    $scope.preson = {
      name: "nir",
      age: 28,
      career: "web Developer"
    };
    $scope.jsonClock = {
      now: new Date()
    };
    updateClock = function() {
      $scope.jsonClock.now = new Date();
    };
    setInterval((function() {
      $scope.$apply(updateClock);
    }), 1000);
    updateClock();
    $scope.jsonClock = {
      now: new Date()
    };
    updateClock = function() {
      $scope.jsonClock.now = new Date();
    };
    setInterval((function() {
      $scope.$apply(updateClock);
    }), 1000);
    updateClock();
    $scope.clock = {
      now: new Date()
    };
    updateClock = function() {
      $scope.clock.now = new Date();
    };
    setInterval((function() {
      $scope.$apply(updateClock);
    }), 1000);
    updateClock();
    $scope.visible = false;
    $scope.visibleBDays = false;
    $scope.bdays = [];
    $scope.lastItem = [];
    return $scope.newBirthday = function() {
      $scope.bdays.push({
        name: $scope.bdayname,
        date: $scope.bdaydate
      });
      $scope.lastItem = {
        name: $scope.bdayname,
        date: $scope.bdaydate
      };
      $scope.bdayname = "";
      $scope.bdaydate = "";
    };
  });

}).call(this);

//# sourceMappingURL=main.map
