// Generated by CoffeeScript 1.7.1
(function() {
  angular.module("ngBookExamples").controller("MoreServiceScope", [
    "$scope", "$parse", function($scope, $parse) {
      console.log("test");
      return $scope.$watch("expr", function(newVal, oldVal, scope) {
        var parseFun;
        if (newVal !== oldVal) {
          parseFun = $parse(newVal);
          scope.parsedExpr = parseFun(scope);
        }
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=services.map
