// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var app;

  app = angular.module("ngBookExamples", ["ngCookies", "ngResource", "ngSanitize", "ngRoute"]);

  app.config(function($routeProvider) {
    $routeProvider.when("/", {
      templateUrl: "views/main.html",
      controller: "DataBindCtrl"
    }).otherwise({
      redirectTo: "/"
    });
    $routeProvider.when("/bday", {
      templateUrl: "views/bday.html",
      controller: "BirthdayCtrl"
    }).otherwise({
      redirectTo: "/"
    });
    $routeProvider.when("/services", {
      templateUrl: "views/services.html",
      controller: "MoreServiceScope"
    }).otherwise({
      redirectTo: "/"
    });
    $routeProvider.when("/filters", {
      templateUrl: "views/filters.html",
      controller: "FilterCrtl"
    }).otherwise({
      redirectTo: "/"
    });
    return $routeProvider.when("/form", {
      templateUrl: "views/form.html",
      controller: "FormCtrl"
    }).otherwise({
      redirectTo: "/"
    });
  });

  app.filter("encodeURIComponent", function() {
    return window.encodeURIComponent;
  });

  app.filter("capitalize", function() {
    return function(input) {
      if (input) {
        return input[0].toUpperCase() + input.slice(1).toLowerCase();
      }
    };
  });

  app.filter("shekelToDollar", function() {
    return function(coin) {
      if (coin) {
        return coin * 3.4880;
      }
    };
  });

  app.filter("shekelToEuro", function() {
    return function(coin) {
      if (coin) {
        return coin * 4.7998;
      }
    };
  });

}).call(this);

//# sourceMappingURL=app.map
