// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  var app;

  app = angular.module("ngBookExamples", ["ngCookies", "ngResource", "ngSanitize", "ngRoute"]);

  app.config(function($routeProvider) {
    return $routeProvider.when("/", {
      templateUrl: "views/main.html",
      controller: "MainCtrl"
    }).otherwise({
      redirectTo: "/"
    });
  });

  app.filter("encodeURIComponent", function() {
    return window.encodeURIComponent;
  });

}).call(this);

//# sourceMappingURL=app.map
